name = "darrylres"
compatibility_date = "2026-06-07"

[build]
command = "node frontend/scripts/remove-cloudflare-redirects.js"

[assets]
directory = "./frontend/dist"
not_found_handling = "single-page-application"
