<?php

namespace App\Http\Controllers\Api\V1;

use App\Events\IotSmokeAlert;
use App\Http\Controllers\Controller;
use App\Models\Incident;
use App\Models\IotDevice;
use App\Support\ApiResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class IotController extends Controller
{
    use ApiResponse;

    public function alert(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'device_id' => ['required', 'string', 'max:50'],
            'smoke_level' => ['required', 'integer', 'min:0'],
            'timestamp' => ['required', 'date'],
        ]);

        if ($validator->fails()) {
            return $this->errorResponse('Validation failed.', $validator->errors()->toArray(), 422);
        }

        $validated = $validator->validated();
        $authenticatedDeviceId = $request->attributes->get('authenticated_iot_device_id');
        $authenticatedDeviceCode = $request->attributes->get('authenticated_iot_device_code');

        $device = IotDevice::query()
            ->where('device_id', $validated['device_id'])
            ->where('is_active', true)
            ->first();

        if (! $device) {
            return $this->errorResponse('Unauthorized IoT device.', [
                'device_id' => ['Device is invalid or inactive.'],
            ], 401);
        }

        if ($device->id !== $authenticatedDeviceId || $device->device_id !== $authenticatedDeviceCode) {
            return $this->errorResponse('Unauthorized IoT device.', [
                'device_id' => ['Device identity mismatch.'],
            ], 401);
        }

        $smokeLevel = (int) $validated['smoke_level'];

        $device->forceFill([
            'last_ping_at' => now(),
        ])->save();

        if ($smokeLevel < $device->smoke_threshold) {
            return $this->successResponse([
                'device_id' => $device->device_id,
                'smoke_level' => $smokeLevel,
                'threshold' => $device->smoke_threshold,
            ], 'Reading received.');
        }

        $duplicateRecentIncident = Incident::query()
            ->where('is_iot_generated', true)
            ->where('device_id', $device->device_id)
            ->whereNotIn('status', ['resolved', 'rejected'])
            ->where('created_at', '>=', now()->subMinutes(10))
            ->exists();

        if ($duplicateRecentIncident) {
            return $this->successResponse([
                'device_id' => $device->device_id,
            ], 'Dedup skipped.');
        }

        $incident = Incident::query()->create([
            'reporter_id' => null,
            'type' => 'fire',
            'description' => sprintf(
                'AUTOMATED ALERT: Smoke sensor %s detected smoke at %s. Reading: %d ppm (threshold: %d ppm).',
                $device->device_id,
                $device->location_name,
                $smokeLevel,
                $device->smoke_threshold
            ),
            'incident_datetime' => now(),
            'latitude' => $device->latitude,
            'longitude' => $device->longitude,
            'address_label' => $device->location_name,
            'status' => 'pending_verification',
            'is_iot_generated' => true,
            'device_id' => $device->device_id,
        ]);

        $incident->logs()->create([
            'changed_by' => null,
            'old_status' => null,
            'new_status' => 'pending_verification',
            'notes' => "Automated IoT smoke alert generated by device {$device->device_id}.",
        ]);

        event(new IotSmokeAlert($device, $incident, $smokeLevel));

        return $this->successResponse([
            'incident_id' => $incident->id,
            'device_id' => $device->device_id,
        ], 'Alert created.', 201);
    }
}
