export const NOTIFICATION_PREFERENCE_OPTIONS = [
  {
    key: 'new_incident',
    label: 'New Incident',
    description: 'Citizen-submitted reports that require command-center attention.',
  },
  {
    key: 'iot_alert',
    label: 'IoT Alert',
    description: 'Automated smoke alerts generated by connected field sensors.',
  },
  {
    key: 'responder_status_change',
    label: 'Responder Status',
    description: 'Operational updates when responders change an incident status.',
  },
  {
    key: 'new_registration',
    label: 'New Registration',
    description: 'Fresh citizen account submissions awaiting admin approval.',
  },
]

export const DEFAULT_NOTIFICATION_PREFERENCES = Object.freeze(
  NOTIFICATION_PREFERENCE_OPTIONS.reduce((accumulator, option) => {
    accumulator[option.key] = true
    return accumulator
  }, {}),
)

const HISTORY_LIMIT = 50
const HISTORY_KEY_PREFIX = 'rescuelink.notification-history'
const PREFERENCES_KEY_PREFIX = 'rescuelink.notification-preferences'

function hasLocalStorage() {
  return typeof window !== 'undefined' && Boolean(window.localStorage)
}

function storageKey(prefix, user) {
  if (!user?.id || !user?.role) {
    return null
  }

  return `${prefix}:${user.role}:${user.id}`
}

function readStorage(key, fallbackValue) {
  if (!key || !hasLocalStorage()) {
    return fallbackValue
  }

  try {
    const raw = window.localStorage.getItem(key)
    return raw ? JSON.parse(raw) : fallbackValue
  } catch {
    return fallbackValue
  }
}

function writeStorage(key, value) {
  if (!key || !hasLocalStorage()) {
    return value
  }

  try {
    window.localStorage.setItem(key, JSON.stringify(value))
  } catch {
    // Ignore storage write failures and continue with in-memory state.
  }

  return value
}

function entryKey(entry) {
  return entry.id ?? entry.local_id
}

export function notificationHistoryStorageKey(user) {
  return storageKey(HISTORY_KEY_PREFIX, user)
}

export function notificationPreferencesStorageKey(user) {
  return storageKey(PREFERENCES_KEY_PREFIX, user)
}

export function browserNotificationPermission() {
  if (typeof window === 'undefined' || !('Notification' in window)) {
    return 'unsupported'
  }

  return window.Notification.permission
}

export async function requestBrowserNotificationPermission() {
  if (typeof window === 'undefined' || !('Notification' in window)) {
    return 'unsupported'
  }

  return window.Notification.requestPermission()
}

export function classifyNotificationEntry(notification) {
  const text = `${notification?.title ?? ''} ${notification?.message ?? ''}`.toLowerCase()
  const link = String(notification?.link ?? '').toLowerCase()

  if (text.includes('announcement') || text.includes('broadcast')) {
    return 'broadcast_message'
  }

  if (link.includes('/admin/registrations') || text.includes('registration')) {
    return 'new_registration'
  }

  if (text.includes('smoke') || text.includes('iot')) {
    return 'iot_alert'
  }

  if (text.includes('new') && text.includes('report')) {
    return 'new_incident'
  }

  if (
    text.includes('updated the incident status')
    || text.includes('resolved')
    || text.includes('responding')
    || text.includes('under assessment')
  ) {
    return 'responder_status_change'
  }

  return 'general'
}

export function notificationTypeMeta(type) {
  switch (type) {
    case 'new_incident':
      return {
        label: 'New Incident',
        badgeClass: 'border-blue-200 bg-blue-50 text-blue-700',
      }
    case 'iot_alert':
      return {
        label: 'IoT Alert',
        badgeClass: 'border-danger/20 bg-danger/10 text-danger',
      }
    case 'responder_status_change':
      return {
        label: 'Responder Status',
        badgeClass: 'border-amber-200 bg-amber-50 text-amber-700',
      }
    case 'new_registration':
      return {
        label: 'New Registration',
        badgeClass: 'border-emerald-200 bg-emerald-50 text-emerald-700',
      }
    case 'broadcast_message':
      return {
        label: 'Broadcast',
        badgeClass: 'border-indigo-200 bg-indigo-50 text-indigo-700',
      }
    default:
      return {
        label: 'General',
        badgeClass: 'border-slate-200 bg-slate-100 text-slate-600',
      }
  }
}

export function loadNotificationPreferences(user) {
  const stored = readStorage(notificationPreferencesStorageKey(user), {})
  return {
    ...DEFAULT_NOTIFICATION_PREFERENCES,
    ...stored,
  }
}

export function saveNotificationPreferences(user, preferences) {
  const nextPreferences = {
    ...DEFAULT_NOTIFICATION_PREFERENCES,
    ...preferences,
  }

  return writeStorage(notificationPreferencesStorageKey(user), nextPreferences)
}

export function normalizeHistoryEntry(notification, source = 'server') {
  const type = notification?.type ?? classifyNotificationEntry(notification)
  const createdAt = notification?.created_at ?? new Date().toISOString()

  return {
    id: notification?.id ?? null,
    local_id:
      notification?.local_id
      ?? notification?.id
      ?? `${type}-${createdAt}-${Math.random().toString(36).slice(2, 8)}`,
    title: notification?.title ?? 'Notification',
    message: notification?.message ?? '',
    link: notification?.link ?? null,
    is_read: Boolean(notification?.is_read),
    created_at: createdAt,
    source,
    type,
  }
}

export function loadNotificationHistory(user) {
  const history = readStorage(notificationHistoryStorageKey(user), [])
  return Array.isArray(history)
    ? history
        .map((entry) => normalizeHistoryEntry(entry, entry?.source ?? 'server'))
        .sort((left, right) => new Date(right.created_at).getTime() - new Date(left.created_at).getTime())
        .slice(0, HISTORY_LIMIT)
    : []
}

export function syncNotificationHistory(user, notifications) {
  const merged = new Map(loadNotificationHistory(user).map((entry) => [entryKey(entry), entry]))

  notifications.forEach((notification) => {
    const normalized = normalizeHistoryEntry(notification, 'server')
    const key = entryKey(normalized)
    const current = merged.get(key)
    merged.set(key, current ? { ...current, ...normalized } : normalized)
  })

  const nextHistory = [...merged.values()]
    .sort((left, right) => new Date(right.created_at).getTime() - new Date(left.created_at).getTime())
    .slice(0, HISTORY_LIMIT)

  return writeStorage(notificationHistoryStorageKey(user), nextHistory)
}

export function appendNotificationHistory(user, notification, source = 'realtime') {
  const nextEntry = normalizeHistoryEntry(notification, source)
  const merged = new Map(loadNotificationHistory(user).map((entry) => [entryKey(entry), entry]))
  const current = merged.get(entryKey(nextEntry))

  merged.set(entryKey(nextEntry), current ? { ...current, ...nextEntry } : nextEntry)

  const nextHistory = [...merged.values()]
    .sort((left, right) => new Date(right.created_at).getTime() - new Date(left.created_at).getTime())
    .slice(0, HISTORY_LIMIT)

  return writeStorage(notificationHistoryStorageKey(user), nextHistory)
}

export function markHistoryEntryRead(user, targetId) {
  const nextHistory = loadNotificationHistory(user).map((entry) =>
    entry.id === targetId || entry.local_id === targetId
      ? { ...entry, is_read: true }
      : entry,
  )

  return writeStorage(notificationHistoryStorageKey(user), nextHistory)
}

export function markAllHistoryEntriesRead(user) {
  const nextHistory = loadNotificationHistory(user).map((entry) => ({ ...entry, is_read: true }))
  return writeStorage(notificationHistoryStorageKey(user), nextHistory)
}

export function maybeShowBrowserNotification(user, notification) {
  if (user?.role !== 'admin' || browserNotificationPermission() !== 'granted') {
    return false
  }

  const preferences = loadNotificationPreferences(user)
  const entry = normalizeHistoryEntry(notification, 'realtime')

  if (!(entry.type in preferences) || !preferences[entry.type]) {
    return false
  }

  const browserNotification = new window.Notification(entry.title, {
    body: entry.message,
    tag: `rescuelink-${entry.type}-${entry.id ?? entry.local_id}`,
  })

  browserNotification.onclick = () => {
    window.focus()

    if (entry.link) {
      window.location.assign(entry.link)
    }
  }

  return true
}
